name: "Resuable code"

on: 
 workflow_call:
    inputs:
        NODE_VERSION:
            type: string
            required: true
        MFE_NAME:
            type: string
            required: true
jobs:
 myjob:
    runs-on: ubuntu-latest


  - name: Tar the vijay.tar build folder, manifest.json, and env.ejs template
        run: |
          tar -cvf $MFE_NAME.tar package.json
          ls -ltr
