name: "Resuable code"

on: 
 workflow_call:
    inputs:
        NODE_VERSION:
            type: string
            required: true
        MFE_NAME:
            type: string
            required: true
jobs:
  release:
    name: Release 
    runs-on: ubuntu-latest


    steps:
      - name: Use Node.js ${{ inputs.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Install Dependencies
        run: |
         # npm config set _auth="$NPM_AUTH"
          npm install
          
      - name: Tar the vijay.tar build folder, manifest.json, and env.ejs template
        run: |
          tar -cvf $MFE_NAME.tar pom.xml deploy-for-test.sh
          ls -ltr
